<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"><link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>FORM VALIDATION</title>
    <style>
    body{
    padding: 0px;
    margin: 0px;
    background-image: url("Untitled design.png");
    background-size: cover;
}
.container{
    position: relative;
}
#formal{
    padding: 20px;
    position: absolute;
    left: 200px;
    top: 60px;
    float: center;
    border-top: 10px solid red;
    border-bottom: 10px solid red;
    border-left: 20px solid gray;
    border-right: 20px solid gray;
    border-radius: 20px;
}
#formv{
    padding: 10px;
}
#formv input{
    border-radius: 15px;
    padding: 10px;
    width: 250px;
    border: none;
    border-bottom: 2px solid gray;
    font-size: 20px;
}
#gender{
    border-radius: 15px;
    padding: 10px;
    width: 250px;
    border: none;
    border-bottom: 2px solid gray;
    font-size: 20px;
    list-style: none;
}
#register{
    border-radius: 15px;
    padding: 10px;
    width: 270px;
    border: none;
    border-bottom: 2px solid gray;
    font-size: 20px;
    background-color: gray;
    cursor: pointer;
    transition: 0.65s ease;
}
#register:hover{
    color: white;
    background-color: red;
    transition: 0.65s ease;
}
#formv input:hover{
    border: none;
}
#eye{
    border: none;
    position: absolute;
    right: 60px;
    top: 190px;
    cursor: pointer;
}
#full{
    position: absolute;
    right: 60px;
    top: 44px;
}
#user{
    position: absolute;
    right: 60px;
    top: 117px;
}
#mail{
    position: absolute;
    right: 60px;
    top: 337px;
}
#num{
    position: absolute;
    right: 60px;
    bottom: 191px;
}
    </style>
</head>
<body>

    <div class="container">

        <form action="#" id="formal">

            <div id="formv">
                <input type="text" id="name" placeholder="FULL NAMES">
                <svg class="bi bi-person" id="full" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8 7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z" clip-rule="evenodd"/>
                </svg>
                <span></span>
            </div>

            <div id="formv">
                <input type="text" id="username" placeholder="USERNAME">
                <svg class="bi bi-person" id="user" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8 7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z" clip-rule="evenodd"/>
                </svg>
                <span></span>
            </div>

            <div id="formv">
                <input type="password" id="password" placeholder="PASSWORD">
                    <svg class="bi bi-eye" onclick="eye()" id="eye" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.134 13.134 0 001.66 2.043C4.12 11.332 5.88 12.5 8 12.5c2.12 0 3.879-1.168 5.168-2.457A13.134 13.134 0 0014.828 8a13.133 13.133 0 00-1.66-2.043C11.879 4.668 10.119 3.5 8 3.5c-2.12 0-3.879 1.168-5.168 2.457A13.133 13.133 0 001.172 8z" clip-rule="evenodd"/>
                        <path fill-rule="evenodd" d="M8 5.5a2.5 2.5 0 100 5 2.5 2.5 0 000-5zM4.5 8a3.5 3.5 0 117 0 3.5 3.5 0 01-7 0z" clip-rule="evenodd"/>
                    </svg>
                <span></span>
            </div>

            <div id="formv">
                <input type="password" id="compassword" placeholder="COMFIRM PASSWORD">
                <span></span>
            </div>

            <div id="formv">
                <input type="email" id="email" placeholder="EMAIL">
                <svg class="bi bi-envelope" id="mail" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M14 3H2a1 1 0 00-1 1v8a1 1 0 001 1h12a1 1 0 001-1V4a1 1 0 00-1-1zM2 2a2 2 0 00-2 2v8a2 2 0 002 2h12a2 2 0 002-2V4a2 2 0 00-2-2H2z" clip-rule="evenodd"/>
                    <path fill-rule="evenodd" d="M.071 4.243a.5.5 0 01.686-.172L8 8.417l7.243-4.346a.5.5 0 01.514.858L8 9.583.243 4.93a.5.5 0 01-.172-.686z" clip-rule="evenodd"/>
                    <path d="M6.752 8.932l.432-.252-.504-.864-.432.252.504.864zm-6 3.5l6-3.5-.504-.864-6 3.5.504.864zm8.496-3.5l-.432-.252.504-.864.432.252-.504.864zm6 3.5l-6-3.5.504-.864 6 3.5-.504.864z"/>
                </svg>
                <span></span>
            </div>

            <div id="formv">
                <input type="text" id="number" placeholder="PHONE NUMBER">
                <svg class="bi bi-phone" id="num" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M11 1H5a1 1 0 00-1 1v12a1 1 0 001 1h6a1 1 0 001-1V2a1 1 0 00-1-1zM5 0a2 2 0 00-2 2v12a2 2 0 002 2h6a2 2 0 002-2V2a2 2 0 00-2-2H5z" clip-rule="evenodd"/>
                    <path fill-rule="evenodd" d="M8 14a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"/>
                </svg>
                <span></span>
            </div>

            <div id="formv">
                <select name="" id="gender">
                    <option value="gend" style="color: gray;" id="gend">GENDER</option>
                    <option value="male">MALE</option>
                    <option value="female">FEMALE</option>
                </select>
            </div>

            <div id="formv">
                <button onclick="reg()" id="register">Register</button>
            </div>

        </form>

    </div>

    <script>
    function reg(){
    var name = document.getElementById('name').value;
    var user = document.getElementById('username').value;
    var pass = document.getElementById('password').value;
    var comp = document.getElementById('compassword').value;
    var mail = document.getElementById('email').value;
    var num = document.getElementById('number').value;
    var gen = document.getElementById('gend').value;
    var gender = document.getElementById('gender').value;
    var eye = document.getElementById('eye').value;


    var atp = mail.indexOf('@');
    var dot = mail.lastIndexOf('.');


    // function eye(){
    //     if (pass.type == "text")
    //         pass.type = "password";
    //     else
    //         pass.type = "text";
    // }
    // eye.addEventListener('click', togglePass);

    if (name === ""){
        alert('Full Name Required..');
        document.getElementById('name').style.borderColor = "red";
        return false;
    } else if (!isNaN(name)){
        alert('Numbers not Allowed..');
        document.getElementById('name').style.borderColor = "red";
        return false;
    } else if (name.search(/[0-9]/) !== -1){
        alert('Numbers not Allowed..');
        document.getElementById('name').style.borderColor = "red";
        return false;
    } else if (name.length < 7){
        alert('Fullnames Most Not Be Less Than Seven..');
        document.getElementById('name').style.borderColor = "red";
        return false;
    } else if (name.length > 25){
        alert('Fullnames Most Not Be More Than Twenty Five..');
        document.getElementById('name').style.borderColor = "red";
        return false;
    } else {
        document.getElementById('name').style.borderColor = "green";
    }


    if (user === ""){
        alert('Username Is Required..');
        document.getElementById('username').style.borderColor = "red";
        return false;
    } else if (!isNaN(user)){
        alert('Letters Are Required..');
        document.getElementById('username').style.borderColor = "red";
        return false;
    } else if (user.length < 4){
        alert('Username Most Be More Than Four..');
        document.getElementById('username').style.borderColor = "red";
        return false;
    } else {
        document.getElementById('username').style.borderColor = "green";
    }


    if (pass === ""){
        alert('Password Is Required..');
        document.getElementById('password').style.borderColor = "red";
        return false;
    } else if (pass.length <= 5){
        alert('Password Most Be More Than Five..');
        document.getElementById('password').style.borderColor = "red";
        return false;
    } else if (pass.search(/[0-9]/) === -1){
        alert('Password Most Contain A Number..');
        document.getElementById('password').style.borderColor = "red";
        return false;
    } else if (pass.search(/[A-Z]/) === -1){
        alert('Password Most Contain A Capital Letter..');
        document.getElementById('password').style.borderColor = "red";
        return false;
    } else if (pass.search(/[a-z]/) === -1){
        alert('Password Most Contain A Small Letter..');
        document.getElementById('password').style.borderColor = "red";
        return false;
    } else if (pass.search(/[!\@\#\$\%\^\*\)\_\-\=\+\|\}\]\;\:\,\.\>\<\?\\]/) === -1){
        alert('Symbols Are Required. ({[ Not Allowed..');
        document.getElementById('password').style.borderColor = "red";
        return false;
    } else {
        document.getElementById('password').style.borderColor = "green";
    }

    if (comp === ""){
        alert('Comfirmpassword is Required..');
        document.getElementById('compassword').style.borderColor = "red"
        return false;
    } else if (comp !== pass){
        alert('Password Not Match..');
        document.getElementById('compassword').style.borderColor = "red";
        document.getElementById('password').style.borderColor = "red";
        return false;
    } else {
        document.getElementById('compassword').style.borderColor = "green";
        document.getElementById('password').style.borderColor = "green";
    }

    if (mail === ""){
        alert('Email is Required..');
        document.getElementById('email').style.borderColor = "red";
        return false;
    } else if (atp < 1 || dot < atp +2 || dot +2 >= mail.length){
        alert('Please Enter A Valid Mail Address');
        document.getElementById('email').style.borderColor = "red";
        return false;
    } else {
        document.getElementById('email').style.borderColor = "green";
    }

    if (num === ""){
        alert('Phone Number is Required..');
        document.getElementById('number').style.borderColor = "red";
        return false;
    } else if (isNaN(num)){
        alert('Phone Number Invalid..');
        document.getElementById('number').style.borderColor = "red";
        return false;
    } else if (num.length !== 14){
        alert('Phone Number Invalid..');
        document.getElementById('number').style.borderColor = "red";
        return false;
    } else if(num.search(/[+\2\3\4]/) === -1){
        alert('Phone Number Most Begin With +234..');
        document.getElementById('number').style.borderColor = "red";
        return false;
    } else {
        document.getElementById('number').style.borderColor = "green";
    }


    if (gen === gender ){
        alert('Select a Gender..');
        document.getElementById('gender').style.borderColor = "red";
        return false;

    } else {
        document.getElementById('gender').style.borderColor = "green";
        alert('You Have Successfully Registered..');
        return true;
    }
}
    </script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    
</body>
</html>
